export interface AccentProfile {
  id: string
  name: string
  description: string
  category: 'fantasy' | 'real-world'
  region: string
  difficulty: 1 | 2 | 3 | 4 | 5
  tags: string[]
  rules: { rule: string; example: string }[]
  eyeDialect: { original: string; accented: string; note: string }[]
  ipa: { word: string; standard: string; accented: string; note: string }[]
  dialectNotes: string
  vocalParams: {
    pitch: number
    pacing: number
    resonance: number
    breathiness: number
    gravel: number
  }
  phrases: string[]
  tips: string[]
  rhythm: string
  anchorVowel: string
  cadenceCheat: string
  npcArchetypes: string[]
  emotionalRange: string[]
}

export type AccentGuide = AccentProfile

export const ACCENT_PROFILES: AccentProfile[] = [
  // =====================================================================
  // FANTASY ACCENTS (1-10)
  // =====================================================================
  {
    id: 'dwarven',
    name: 'Dwarven (Scottish-Inspired)',
    description: 'Gruff, rolling Rs, clipped consonants. Think Gimli meets a Highland warrior.',
    category: 'fantasy',
    region: 'Mountain Kingdoms',
    difficulty: 2,
    tags: ['gruff', 'rolling-r', 'clipped', 'hearty'],
    rules: [
      { rule: 'Roll your Rs heavily', example: '"Rrright then, let\'s get to worrk"' },
      { rule: 'Replace "to" with "tae"', example: '"I\'m goin\' tae the forge"' },
      { rule: 'Use "aye" instead of "yes"', example: '"Aye, that\'ll do"' },
      { rule: 'Drop the "g" in "-ing" words', example: '"I\'m thinkin\' about hammerin\'"' },
      { rule: 'Clipped, punchy sentences', example: '"Stone holds. Always has."' },
      { rule: 'Replace "not" with "nae"', example: '"I\'ll nae stand for it"' },
    ],
    eyeDialect: [
      { original: 'right', accented: 'rrright', note: 'Heavy trill on initial R' },
      { original: 'to the', accented: 'tae the', note: '"to" always becomes "tae"' },
      { original: 'thinking', accented: "thinkin'", note: 'Drop trailing -g' },
      { original: 'not', accented: 'nae', note: 'Scottish negation' },
    ],
    ipa: [
      { word: 'right', standard: '/\u0279a\u026At/', accented: '/ra\u026At/', note: 'Alveolar trill replaces approximant' },
      { word: 'not', standard: '/n\u0252t/', accented: '/ne\u02D0/', note: '"nae" with lengthened vowel' },
      { word: 'stone', standard: '/st\u0259\u028An/', accented: '/sto\u02D0n/', note: 'Monophthong, no glide' },
    ],
    dialectNotes: 'The Dwarven accent draws from Scottish Gaelic phonology mapped onto Common. The key is chest resonance combined with clipped delivery \u2014 every word is struck like a hammer on an anvil. Avoid going too comedic; real dwarves speak with earned authority.',
    vocalParams: { pitch: 3, pacing: 4, resonance: 9, breathiness: 2, gravel: 7 },
    phrases: [
      "By Moradin's beard, what manner of beast is that?",
      "Aye, the ale's good, but it's nae as good as home.",
      'Ye think ye can outdrink a dwarf? Rrrridiculous.',
      'The stone remembers what flesh forgets.',
      "I'll nae be leavin' without me axe.",
      "Tae the deep roads, then. Nae time fer dallyin'.",
      'Every hammer blow tells a story. Listen.',
      "Gold's fine, but iron keeps ye alive.",
    ],
    tips: [
      'Lower your pitch slightly \u2014 dwarves speak from the chest, place your hand on your sternum and feel the vibration',
      'Practice the rolled R by placing your tongue tip behind your upper teeth and pushing air across it; start with "drrr" warmups',
      'Add weight to consonants by holding them a fraction longer: T, K, and D should feel punchy and percussive',
    ],
    rhythm: 'Steady, marching cadence. Short sentences with heavy emphasis on key words. Pauses before important declarations.',
    anchorVowel: 'Short "o" as in "stone" \u2014 round and solid, monophthong /o\u02D0/ instead of diphthong',
    cadenceCheat: "Speak like you're giving orders between hammer strikes.",
    npcArchetypes: ['Grizzled smith or mining foreman', 'Stoic clan elder', 'Loud and loyal tavern regular'],
    emotionalRange: ['Stubborn determination', 'Gruff tenderness', 'Righteous fury'],
  },
  {
    id: 'elvish',
    name: 'Elvish (Welsh/Ethereal)',
    description: 'Melodic, flowing vowels, soft consonants. Timeless and slightly distant.',
    category: 'fantasy',
    region: 'Sylvan Courts',
    difficulty: 3,
    tags: ['melodic', 'flowing', 'ethereal', 'formal'],
    rules: [
      { rule: 'Elongate vowels slightly', example: '"The liiight of the mooon..."' },
      { rule: 'Soften hard consonants', example: '"Gently" not "GENT-ly"' },
      { rule: 'Use formal/archaic phrasing', example: '"It would seem" instead of "I think"' },
      { rule: 'Speak slightly slower than normal', example: 'Let each word breathe' },
      { rule: 'Raise pitch slightly at end of phrases', example: 'Musical, questioning lilt' },
      { rule: 'Avoid contractions', example: '"I will not" instead of "I won\'t"' },
    ],
    eyeDialect: [
      { original: 'light', accented: 'liiight', note: 'Elongated central vowel' },
      { original: 'moon', accented: 'mooon', note: 'Extended vowel for reverence' },
      { original: 'gently', accented: 'gen-tly', note: 'Softer onset, less percussive' },
      { original: "won't", accented: 'will not', note: 'No contractions ever' },
    ],
    ipa: [
      { word: 'light', standard: '/la\u026At/', accented: '/la\u02D0\u026At/', note: 'Lengthened nucleus' },
      { word: 'gentle', standard: '/\u02C8d\u0292\u025Bnt\u0259l/', accented: '/\u02C8\u0261\u025Bnt\u0259l/', note: 'Unaffricated stop, softer onset' },
      { word: 'forest', standard: '/\u02C8f\u0252r\u026Ast/', accented: '/\u02C8fo\u02D0r\u025Bst/', note: 'Elongated vowel, Welsh-like' },
    ],
    dialectNotes: 'Elvish speech patterns borrow from Welsh musicality \u2014 the rising and falling inflections that make every statement sound half-sung. The key is not speed but flow; consonants dissolve into vowels, and silence between phrases carries meaning. Never rush.',
    vocalParams: { pitch: 7, pacing: 3, resonance: 5, breathiness: 7, gravel: 1 },
    phrases: [
      'The trees whisper of what was, and what shall yet be.',
      'I have watched centuries turn, and still this beauty moves me.',
      'Your haste blinds you to what patience would reveal.',
      'The stars remember your name, even if you have forgotten.',
      'There is grace in stillness that motion cannot achieve.',
      'The dawn does not hurry. Neither shall I.',
      'Every leaf that falls tells a story older than your kingdom.',
      'Listen \u2014 the wind carries more truth than any sage.',
    ],
    tips: [
      'Keep your tongue relaxed and forward in the mouth \u2014 tension kills the Elvish sound',
      'Breathe between phrases, not mid-phrase; each sentence should be one flowing breath',
      'Use your upper register without going falsetto \u2014 aim for resonance in the nasal and sinus cavities',
    ],
    rhythm: 'Flowing, almost musical. Longer sentences that build and resolve like waves. No rush.',
    anchorVowel: 'Long "ah" as in "star" \u2014 open and resonant, held longer than natural',
    cadenceCheat: "Speak like you're narrating a dream you had a century ago.",
    npcArchetypes: ['Ancient sage or lorekeeper', 'Otherworldly emissary', 'Melancholy ranger or warden'],
    emotionalRange: ['Quiet sorrow', 'Serene wisdom', 'Cold, precise anger'],
  },
  {
    id: 'orcish',
    name: 'Orcish (Guttural)',
    description: 'Deep, guttural, emphasis on hard consonants. Raw power in every word.',
    category: 'fantasy',
    region: 'Warlands',
    difficulty: 2,
    tags: ['guttural', 'aggressive', 'primal', 'direct'],
    rules: [
      { rule: 'Drop to your lowest comfortable pitch', example: 'Speak from the gut, not the throat' },
      { rule: 'Emphasize hard consonants: K, G, T, D', example: '"KILL" not "kill"' },
      { rule: 'Shorten vowels aggressively', example: '"Strng" instead of "Strong"' },
      { rule: 'Use simple, direct sentences', example: '"Fight now. Talk later."' },
      { rule: 'Growl slightly on emphasized words', example: '"I will CRUSH them"' },
      { rule: 'Replace complex words with simpler ones', example: '"Break" not "dismantle"' },
    ],
    eyeDialect: [
      { original: 'strong', accented: 'strng', note: 'Vowel compression' },
      { original: 'kill', accented: 'KILL', note: 'Percussive emphasis on hard sounds' },
      { original: 'destroy', accented: 'CRUSH', note: 'Simpler, more visceral word' },
      { original: 'certainly', accented: 'yah', note: 'Minimal syllables' },
    ],
    ipa: [
      { word: 'strong', standard: '/str\u0252\u014B/', accented: '/str\u014B/', note: 'Deleted vowel nucleus' },
      { word: 'kill', standard: '/k\u026Al/', accented: '/k\u02B0\u026Al/', note: 'Aspirated, explosive onset' },
      { word: 'blood', standard: '/bl\u028Ad/', accented: '/bl\u028Ad\u02D0/', note: 'Elongated final stop' },
    ],
    dialectNotes: "Orcish is less about specific phoneme shifts and more about delivery \u2014 raw energy channeled through minimal syllables. The jaw stays tense, the breath is audible, and silences between phrases feel like the calm before a charge. Don't try to be eloquent; be forceful.",
    vocalParams: { pitch: 2, pacing: 6, resonance: 8, breathiness: 3, gravel: 9 },
    phrases: [
      'Gruumsh sees all. Gruumsh judges all.',
      'Words are weak. Axe is strong.',
      'You talk. I fight. We see who wins.',
      'Blood calls to blood. I answer.',
      'The weak hide behind walls. I AM the wall.',
      'Pain is teacher. Best teacher.',
      'You smell of fear. Good.',
      'War drum beats. We march.',
    ],
    tips: [
      'Clench your jaw slightly while speaking \u2014 let sound push through the teeth',
      'Breathe audibly through the nose between phrases; the silence is part of the voice',
      'Let emotion drive volume \u2014 anger means louder, not faster',
    ],
    rhythm: 'Staccato bursts. Short, punchy phrases with aggressive pauses. Like war drums.',
    anchorVowel: 'Short "uh" as in "blood" \u2014 guttural and primal, pulled deep into the throat',
    cadenceCheat: 'Speak like each sentence is a punch landing.',
    npcArchetypes: ['War chief or raiding captain', 'Tribal shaman speaking prophecy', 'Arena champion'],
    emotionalRange: ['Battle fury', 'Quiet grief', 'Begrudging respect'],
  },
  {
    id: 'noble',
    name: 'Noble Court (RP English)',
    description: 'Crisp received pronunciation, measured delivery, effortless authority.',
    category: 'fantasy',
    region: 'Royal Courts',
    difficulty: 3,
    tags: ['refined', 'authoritative', 'measured', 'condescending'],
    rules: [
      { rule: 'Elongate vowels precisely', example: '"Rahther" not "Rather"' },
      { rule: 'Crisp T sounds (never dropped)', example: '"WaTer" not "Wa\'er"' },
      { rule: 'Non-rhotic: drop R after vowels', example: '"Fah" not "Far"' },
      { rule: 'Use formal vocabulary naturally', example: '"Indeed" instead of "Yeah"' },
      { rule: 'Measured pace \u2014 never rush', example: 'Every word has its place' },
      { rule: 'Slight condescension baked in', example: '"How... quaint."' },
    ],
    eyeDialect: [
      { original: 'rather', accented: 'rahther', note: 'Open back vowel, precise T' },
      { original: 'water', accented: 'WAH-tah', note: 'Non-rhotic, crisp T' },
      { original: 'far', accented: 'fah', note: 'Dropped post-vocalic R' },
      { original: 'yeah', accented: 'indeed', note: 'Lexical upgrade' },
    ],
    ipa: [
      { word: 'rather', standard: '/\u02C8\u0279\u00E6\u00F0\u0259\u0279/', accented: '/\u02C8\u0279\u0251\u02D0\u00F0\u0259/', note: 'Open back vowel, non-rhotic' },
      { word: 'water', standard: '/\u02C8w\u0254\u02D0t\u0259\u0279/', accented: '/\u02C8w\u0254\u02D0t\u0259/', note: 'Crisp medial T, dropped final R' },
      { word: 'bath', standard: '/b\u00E6\u03B8/', accented: '/b\u0251\u02D0\u03B8/', note: 'Broad A, the hallmark' },
    ],
    dialectNotes: "The Noble accent is RP filtered through fantasy aristocracy. The core is control \u2014 every syllable is deliberate, every pause is a power move. The trick is making it sound natural rather than performative; true nobles don't try to sound posh, they simply are.",
    vocalParams: { pitch: 5, pacing: 3, resonance: 6, breathiness: 4, gravel: 2 },
    phrases: [
      'I dare say, this establishment has seen better days.',
      'One does not simply demand an audience with me.',
      'How positively dreadful. Do carry on, though.',
      'The affairs of commoners are... not my concern.',
      'I shall consider your proposal. Eventually.',
      'Your enthusiasm is... noted. And rather exhausting.',
      'I trust you will see yourself out. The door is that way.',
      'How terribly inconvenient for everyone involved.',
    ],
    tips: [
      'Keep your chin slightly elevated \u2014 it naturally shifts resonance forward and upward',
      'Speak as though every word costs gold and you are wealthy enough not to care',
      'Practice the non-rhotic R by saying "far" as "fah" \u2014 the tongue never curls back',
    ],
    rhythm: 'Deliberate and measured. Long, structured sentences with strategic pauses. Never hurried.',
    anchorVowel: 'Long "ah" as in "bath" \u2014 open and unhurried, jaw drops, tongue low and back',
    cadenceCheat: "Speak like you have all the time in the world and everyone else is wasting it.",
    npcArchetypes: ['Ruling monarch or regent', 'Diplomatic envoy', 'Wealthy patron who funds adventures'],
    emotionalRange: ['Icy displeasure', 'Warm condescension', 'Genuine noblesse oblige'],
  },
  {
    id: 'pirate',
    name: 'Pirate (West Country)',
    description: 'Swashbuckling, rolling Rs, dropped Hs, playful menace.',
    category: 'fantasy',
    region: 'High Seas',
    difficulty: 1,
    tags: ['swashbuckling', 'playful', 'rough', 'nautical'],
    rules: [
      { rule: 'Roll your Rs (softer than Dwarven)', example: '"Arrr, the sea calls"' },
      { rule: 'Drop H sounds', example: '"\'ere" not "here"' },
      { rule: 'Replace "my" with "me"', example: '"Where\'s me rum?"' },
      { rule: 'Add nautical vocabulary', example: '"Avast!", "Landlubber", "Scallywag"' },
      { rule: 'Use "be" instead of "is/am"', example: '"I be the captain \'ere"' },
      { rule: 'End sentences with emphasis words', example: '"...savvy?", "...aye?"' },
    ],
    eyeDialect: [
      { original: 'here', accented: "'ere", note: 'Dropped H' },
      { original: 'my', accented: 'me', note: 'Possessive shift' },
      { original: 'is', accented: 'be', note: 'Pirate copula' },
      { original: 'hello', accented: 'ahoy', note: 'Nautical greeting' },
    ],
    ipa: [
      { word: 'here', standard: '/h\u026A\u0259/', accented: '/\u026A\u0259/', note: 'H-dropping' },
      { word: 'arr', standard: '\u2014', accented: '/\u0251\u02D0r/', note: 'Extended rhotic, signature sound' },
      { word: 'treasure', standard: '/\u02C8tr\u025B\u0292\u0259/', accented: '/\u02C8tr\u025B\u0292\u0259r/', note: 'Rhotic coda added' },
    ],
    dialectNotes: "The pirate accent is West Country English exaggerated for the high seas. It's the most forgiving accent to attempt because audiences expect and enjoy over-the-top delivery. The secret is joy: pirates love being pirates. Let that energy drive every line.",
    vocalParams: { pitch: 4, pacing: 6, resonance: 6, breathiness: 3, gravel: 5 },
    phrases: [
      "The sea don't care about yer fancy titles, savvy?",
      "Every storm I've survived made me stronger, aye.",
      "There be treasure 'ere, I can smell it in me bones.",
      "Ye'll walk the plank for that, ye scurvy dog!",
      "Wind in the sails and gold in the hold \u2014 that be livin'.",
      "I've sailed seas ye can't even name, landlubber.",
      'Dead men tell no tales, but their maps do, savvy?',
      "The kraken? Aye, I've met 'er. She owes me a ship.",
    ],
    tips: [
      'Speak with a grin \u2014 shape your mouth around a smile and the vocal quality shifts naturally',
      'Lean into the performance; this accent rewards commitment and energy over precision',
      'Vary rapidly between threatening and jovial to capture the pirate duality',
    ],
    rhythm: 'Swinging, sea-shanty cadence. Playful ups and downs. Sentences that roll like waves.',
    anchorVowel: 'Broad "arr" \u2014 open, rhotic, drawn out like a sail catching wind',
    cadenceCheat: "Speak like you're telling a tall tale over rum at sunset.",
    npcArchetypes: ['Swashbuckling captain or first mate', 'Weathered harbor merchant', 'Reformed pirate turned quest-giver'],
    emotionalRange: ['Boisterous joy', 'Threatening menace', 'Wistful longing for the sea'],
  },
  {
    id: 'fey',
    name: 'Fey (Ethereal/Whimsical)',
    description: 'Airy, playful, unpredictable. Singsong quality with sudden shifts.',
    category: 'fantasy',
    region: 'Feywild',
    difficulty: 4,
    tags: ['whimsical', 'unpredictable', 'musical', 'trickster'],
    rules: [
      { rule: 'Speak in a higher, lighter register', example: 'Airy and delicate' },
      { rule: 'Elongate S sounds slightly', example: '"Yesss, how delightful"' },
      { rule: 'Use riddles and double meanings', example: '"The answer is never the question"' },
      { rule: 'Shift tone mid-sentence unexpectedly', example: '"How lovely\u2014 DON\'T touch that."' },
      { rule: 'Giggle or hum between thoughts', example: '"Hmm, curious, very curious..."' },
      { rule: 'Never give a straight answer', example: '"Perhaps. Perhaps not. Perhaps both."' },
    ],
    eyeDialect: [
      { original: 'yes', accented: 'yesss', note: 'Sibilant extension for delight' },
      { original: 'interesting', accented: 'cu-ri-ous', note: 'Broken into musical syllables' },
      { original: 'goodbye', accented: 'farewell... for now', note: 'Ominous trailing' },
      { original: 'no', accented: 'not precisely', note: 'Never a direct refusal' },
    ],
    ipa: [
      { word: 'yes', standard: '/j\u025Bs/', accented: '/j\u025Bs\u02D0\u02D0/', note: 'Prolonged sibilant' },
      { word: 'curious', standard: '/\u02C8kj\u028A\u0259\u0279i\u0259s/', accented: '/\u02C8k\u028A.\u0279i.\u0259s/', note: 'Each syllable a separate note' },
      { word: 'mortal', standard: '/\u02C8m\u0254\u02D0t\u0259l/', accented: '/\u02C8m\u0254\u02D0\u02D0.t\u0259l/', note: 'Lingering, almost pitying' },
    ],
    dialectNotes: "Fey speech is less a dialect and more a performance style. The voice should feel like it exists slightly outside of reality \u2014 pitch shifts that don't quite follow human patterns, rhythms that feel musical but never resolve predictably. The core challenge is unpredictability without chaos.",
    vocalParams: { pitch: 8, pacing: 5, resonance: 4, breathiness: 8, gravel: 1 },
    phrases: [
      'Names have power, little mortal. I shall not give you mine so easily.',
      'Time? Time is a river that flows in circles here.',
      'You amuse me. That is either very good or very, very bad for you.',
      "The flowers here sing at midnight. Don't listen. Or do. It matters not.",
      'A bargain, you say? Oh, how delicious. Tell me more...',
      'Every gift is a debt, and every debt is a door.',
      "I was old when your gods were young. Isn't that funny?",
      'The truth? Oh, I never deal in anything so dull.',
    ],
    tips: [
      'Smile while speaking \u2014 it naturally lifts the soft palate and brightens the vocal tone',
      'Let your pitch dance within each sentence; monotone kills the Fey quality instantly',
      'Practice the mid-sentence tone shift: start sweet, pivot to sharp, return to sweet',
    ],
    rhythm: 'Musical and unpredictable. Singsong patterns that break without warning. Playful pauses.',
    anchorVowel: 'Elongated "ooo" as in "moon" \u2014 ethereal and shifting, held with breathy resonance',
    cadenceCheat: "Speak like you know a secret about the person you're talking to.",
    npcArchetypes: ['Archfey patron or ruler', 'Trickster sprite or satyr', 'Fey merchant with strange wares'],
    emotionalRange: ['Mercurial delight', 'Unsettling calm', 'Sudden, precise cruelty'],
  },
  {
    id: 'infernal',
    name: 'Infernal/Tiefling (Eastern European)',
    description: 'Dark, precise, with clipped consonants and a subtle Slavic undertone. Authority earned through intimidation and intellect.',
    category: 'fantasy',
    region: 'Nine Hells / Eastern European analog',
    difficulty: 4,
    tags: ['dark', 'precise', 'slavic', 'intimidating', 'intellectual'],
    rules: [
      { rule: 'Harden all consonants \u2014 each one is deliberate and sharp', example: '"I do not forGET. I do not forGIVE."' },
      { rule: 'Use a slight velar or uvular quality on R sounds', example: 'A heavier R, almost French/German, not rolled Scottish-style' },
      { rule: 'Front vowels become more closed and precise', example: '"Deed" instead of a relaxed "did"' },
      { rule: 'Speak with controlled, even pacing \u2014 never rush, never stumble', example: 'Each word placed like a chess piece' },
      { rule: 'Drop articles occasionally for a foreign-syntax feel', example: '"Contract is binding" not "The contract is binding"' },
      { rule: 'Use formal, legalistic phrasing with implied threat', example: '"You will find the terms... non-negotiable."' },
    ],
    eyeDialect: [
      { original: 'I will remember this', accented: 'I vill remember this', note: 'W shifts toward V in onset position' },
      { original: 'What do you want?', accented: 'Vhat do you vant?', note: 'W-to-V shift throughout' },
      { original: 'That is very interesting', accented: 'That is... wery interesting', note: 'V can also shift to W in some positions for variety' },
      { original: 'The deal is done', accented: 'Deal is done. There is no returning.', note: 'Drop article, add ominous extension' },
    ],
    ipa: [
      { word: 'will', standard: '/w\u026Al/', accented: '/v\u026Al/', note: 'Labiodental V replaces bilabial W' },
      { word: 'remember', standard: '/\u0279\u026A\u02C8m\u025Bmb\u0259\u0279/', accented: '/\u0280\u026A\u02C8m\u025Bmb\u0259\u0280/', note: 'Uvular R replaces approximant' },
      { word: 'deal', standard: '/di\u02D0l/', accented: '/d\u02B0i\u02D0\u026B/', note: 'Aspirated D, dark L final' },
    ],
    dialectNotes: 'Infernal speech combines Eastern European phonology with a legalistic precision. The rhythm is measured and relentless \u2014 no wasted syllables, no emotional outbursts. When an Infernal speaker raises their voice, it is a deliberate choice, not a loss of control. The W-to-V shift is the most recognizable marker, but the real key is the pacing: every sentence feels like a clause in a contract.',
    vocalParams: { pitch: 4, pacing: 3, resonance: 7, breathiness: 2, gravel: 5 },
    phrases: [
      'Every soul has a price. I am merely... efficient at discovery.',
      'You misunderstand. I am not threatening you. I am informing you.',
      'The contract was clear. You simply failed to read the fine print.',
      'Trust? Trust is for those who cannot enforce agreements.',
      'I have waited centuries for this moment. A few more minutes will not matter.',
      'Your anger amuses me. Rage is just leverage I have not yet used.',
      'There is always a deal to be made. The question is what you are willing to pay.',
      'I do not lie. I have never needed to. The truth is far more devastating.',
    ],
    tips: [
      'Keep your jaw tighter than normal \u2014 this naturally sharpens consonants and narrows vowels',
      'Practice the W-to-V shift: say "very well" as "wery vell" until the swap feels natural',
      'Slow your pacing by 30% from conversational speed \u2014 control is the core of this accent',
    ],
    rhythm: 'Measured, relentless, and precise. Each sentence is delivered like a legal verdict \u2014 unhurried, final, and leaving no room for argument.',
    anchorVowel: 'The tight /i\u02D0/ as in "deal," "see," "binding" \u2014 narrow, precise, no diphthong drift',
    cadenceCheat: 'Speak like a chess player announcing checkmate \u2014 calm, certain, already three moves ahead.',
    npcArchetypes: ['Devil or fiend negotiator', 'Tiefling warlock or advisor', 'Infernal bureaucrat or judge'],
    emotionalRange: ['Cold amusement', 'Calculated menace', 'Patient, absolute certainty'],
  },
  {
    id: 'draconic',
    name: 'Draconic (Ancient/Resonant)',
    description: 'Deep, resonant, with sibilant undertones and an ancient weight behind every syllable. The voice of creatures older than civilizations.',
    category: 'fantasy',
    region: 'Dragon lairs and ancient ruins / No single real-world analog',
    difficulty: 5,
    tags: ['ancient', 'resonant', 'sibilant', 'powerful', 'primal'],
    rules: [
      { rule: 'Extend all sibilants: S, SH, Z become drawn-out hisses', example: '"Yesss, little one. I sssee you."' },
      { rule: 'Speak from the deepest chest resonance you can sustain', example: 'Feel the vibration in your ribcage, not your throat' },
      { rule: 'Add a rumbling undertone on stressed words, like a distant growl', example: '"I am ANCIENT" \u2014 the capitalized word vibrates' },
      { rule: 'Use archaic, declarative syntax \u2014 state truths, never ask', example: '"You will kneel." Not "Would you mind kneeling?"' },
      { rule: 'Pause significantly between phrases as if time means nothing', example: '"I have waited... (long pause) ...and now you come."' },
      { rule: 'Elongate vowels on words of power or importance', example: '"Goooold. Fiiiire. Deeeeath."' },
    ],
    eyeDialect: [
      { original: 'I see you', accented: 'I sssee you', note: 'Extended sibilant on "see"' },
      { original: 'Come here', accented: 'Approach... if you dare', note: 'Replace commands with challenges' },
      { original: 'That is mine', accented: 'That isss MINE. It hasss alwaysss been mine.', note: 'Possessiveness with sibilant saturation' },
      { original: 'You are brave', accented: 'You are bold. Foolishhh... but bold.', note: 'Backhanded compliment with extended SH' },
    ],
    ipa: [
      { word: 'see', standard: '/si\u02D0/', accented: '/s\u02D0\u02D0i\u02D0/', note: 'Prolonged onset sibilant' },
      { word: 'fire', standard: '/fa\u026A\u0259/', accented: '/fa\u026A\u02D0\u0259\u0280/', note: 'Extended diphthong, uvular R' },
      { word: 'gold', standard: '/\u0261\u0259\u028Ald/', accented: '/\u0261o\u02D0\u02D0ld/', note: 'Extended monophthong, savoring the word' },
    ],
    dialectNotes: 'Draconic speech should feel geological \u2014 slow, massive, and inevitable. The sibilants evoke the serpentine origin, while the deep resonance conveys sheer physical size. Syntax is declarative and absolute; dragons do not ask, suggest, or hedge. The pauses are as important as the words \u2014 they communicate that this creature operates on a different timescale entirely.',
    vocalParams: { pitch: 1, pacing: 2, resonance: 10, breathiness: 3, gravel: 7 },
    phrases: [
      'I was ancient when your ancestors were learning to make fire.',
      'Your treasures are trinkets. Your kingdoms are sandcastles. But you amuse me.',
      'Every coin in this hoard has a story. Most of them end in screaming.',
      'You speak of courage as though it were a shield. It is not.',
      'I do not sleep. I wait. There is a difference.',
      'The last mortal who stood where you stand... I do not recall their name. I recall their taste.',
      'Speak your piece, small one. My patience is vast, but not infinite.',
      'Fire is not my weapon. Fire is my language.',
    ],
    tips: [
      'Drop your larynx by yawning slightly before speaking \u2014 this opens the chest resonance dramatically',
      'Practice the sibilant extension by sustaining an "sss" for five seconds before each sentence in warmups',
      'Add a subtle vibrato or rumble on emphasized words by engaging your diaphragm muscles',
    ],
    rhythm: 'Glacial and titanic. Enormous pauses between thoughts. When words come, they land like boulders. The rhythm communicates that you are older than time and in no hurry whatsoever.',
    anchorVowel: 'The extended /o\u02D0/ as in "gold," "old," "hoard" \u2014 round, deep, savored like a dragon savors its treasure',
    cadenceCheat: 'Speak as if every sentence is carved in stone and will outlast civilizations.',
    npcArchetypes: ['Ancient wyrm atop its hoard', 'Dragonborn elder or philosopher', 'Draconic oracle or deity avatar'],
    emotionalRange: ['Vast, indifferent amusement', 'Slow-building, apocalyptic rage', 'Ancient, bone-deep pride'],
  },
  {
    id: 'goblinoid',
    name: 'Goblinoid (Cockney-Influenced)',
    description: 'Fast, clipped, street-smart. Dropped Hs, glottal stops, and rapid-fire delivery with cunning underneath.',
    category: 'fantasy',
    region: 'Undercities and warrens / East London Cockney analog',
    difficulty: 2,
    tags: ['fast', 'cunning', 'street-smart', 'cockney', 'scrappy'],
    rules: [
      { rule: 'Drop H sounds at word beginnings', example: '"\'ere, \'ave a look at this, will ya?"' },
      { rule: 'Replace T with a glottal stop between vowels and at word ends', example: '"bo\'le" for "bottle," "wha\'" for "what"' },
      { rule: 'Use TH-fronting: "th" becomes "f" or "v"', example: '"fink" for "think," "bruvver" for "brother"' },
      { rule: 'Speak fast and clipped \u2014 words tumble over each other', example: 'Rapid-fire delivery, barely pausing for breath' },
      { rule: 'Add street slang and underworld vocabulary', example: '"nick" for steal, "scarper" for run, "dodgy" for suspicious' },
      { rule: 'Use "innit" as a universal tag question', example: '"Pretty clever, innit?" "Dangerous, innit?"' },
    ],
    eyeDialect: [
      { original: 'here, have a look', accented: "'ere, 'ave a look", note: 'H-dropping throughout' },
      { original: 'I think that is suspicious', accented: "I fink that's well dodgy, innit", note: 'TH-fronting, slang, tag question' },
      { original: 'bottle of water', accented: "bo'le o' wa'er", note: 'Glottal stops replacing T' },
      { original: 'brother', accented: 'bruvver', note: 'TH-fronting: voiced TH becomes V' },
    ],
    ipa: [
      { word: 'think', standard: '/\u03B8\u026A\u014Bk/', accented: '/f\u026A\u014Bk/', note: 'TH-fronting to /f/' },
      { word: 'bottle', standard: '/\u02C8b\u0252tl\u0329/', accented: '/\u02C8b\u0252\u0294l\u0329/', note: 'Glottal stop replaces medial T' },
      { word: 'have', standard: '/h\u00E6v/', accented: '/\u00E6v/', note: 'H-dropping' },
    ],
    dialectNotes: 'Goblinoid speech is all about speed and survival instinct. Words come fast, sentences overlap, and there is always an angle being worked. The Cockney base provides the phonological framework, but the goblinoid twist is the manic energy underneath \u2014 these are creatures who think fast because hesitation gets you eaten. The humor is sharp and self-deprecating.',
    vocalParams: { pitch: 7, pacing: 9, resonance: 3, breathiness: 2, gravel: 4 },
    phrases: [
      "Right, so 'ere's the fing \u2014 we go in, we grab it, we scarper. Simple, innit?",
      "I ain't stupid, I'm just... strategically flexible, yeah?",
      "You want loyalty? Pay better. That's goblin economics, that is.",
      "Oi! That's MY shinies! I found 'em fair and... well, I found 'em.",
      "Look, I ain't sayin' it's a trap. I'm sayin' it SMELLS like a trap, innit?",
      "Run first, fink later. That's 'ow you get old in this business.",
      "Every big folk finks we're stupid. That's our best weapon, that is.",
      "Yeah, I nicked it. What of it? Wasn't nailed down, was it?",
    ],
    tips: [
      'Speed is key \u2014 practice speaking 20-30% faster than your comfortable pace',
      'For the glottal stop, imagine saying "uh-oh" \u2014 that catch in your throat replaces T sounds',
      'Keep your voice nasal and forward in the mouth, as if speaking through your nose',
    ],
    rhythm: 'Rapid-fire and staccato. Words pile up fast, punctuated by brief pauses for emphasis or scheming. Like a small creature that never stops moving.',
    anchorVowel: 'The Cockney /a\u026A/ shifting toward /\u0254\u026A/ as in "right" becoming "roight" \u2014 marks the street origin',
    cadenceCheat: "Speak like you're pitching a scheme and you only have ten seconds before someone catches you.",
    npcArchetypes: ['Goblin scout or informant', 'Black-market fence or dealer', 'Kobold inventor or trap-maker'],
    emotionalRange: ['Manic excitement', 'Weaselly self-preservation', 'Surprising loyalty under pressure'],
  },
  {
    id: 'undead',
    name: 'Undead/Lich (Hollow/Whispered)',
    description: 'Hollow, dry, whispered with unnatural pauses. The voice of something that should not still be speaking but cannot stop.',
    category: 'fantasy',
    region: 'Shadowfell and necropolises / No single real-world analog',
    difficulty: 4,
    tags: ['hollow', 'whispered', 'eerie', 'dry', 'ancient'],
    rules: [
      { rule: 'Reduce volume to a stage whisper \u2014 breathy but audible', example: 'Not quiet mumbling; project a whisper like an actor' },
      { rule: 'Add unnatural pauses mid-sentence where they do not belong', example: '"I was... once... like you. That was... a long time ago."' },
      { rule: 'Devoice final consonants \u2014 let words trail into breath', example: '"Death" becomes almost "Deh-thh" with a trailing hiss' },
      { rule: 'Flatten emotional affect \u2014 monotone with occasional eerie spikes', example: 'Everything is delivered at the same level until something triggers intensity' },
      { rule: 'Use past tense to describe present experiences', example: '"I remembered pain" instead of "I feel pain"' },
      { rule: 'Speak as if breath is an afterthought \u2014 no natural breathing rhythm', example: 'Sentences break in odd places because lungs no longer drive the voice' },
    ],
    eyeDialect: [
      { original: 'I remember being alive', accented: 'I... remember. Being... alive. Yesss.', note: 'Fragmented, paused, trailing sibilant' },
      { original: 'Come closer', accented: 'Come... closssser', note: 'Extended sibilant, eerie pause' },
      { original: 'You will die', accented: 'You will... end. As all things... end.', note: 'Euphemistic, philosophical replacement' },
      { original: 'That hurts', accented: 'Pain. I... knew that word once.', note: 'Past tense, disconnected affect' },
    ],
    ipa: [
      { word: 'death', standard: '/d\u025B\u03B8/', accented: '/d\u025B\u02D0\u03B8\u02B0/', note: 'Extended vowel, aspirated final' },
      { word: 'closer', standard: '/\u02C8kl\u0259\u028Az\u0259/', accented: '/\u02C8kl\u0259\u028As\u02D0\u0259/', note: 'Devoiced Z to S, extended' },
      { word: 'remember', standard: '/\u0279\u026A\u02C8m\u025Bmb\u0259/', accented: '/\u0279\u026A\u02C8m\u025Bm\u02D0b\u0259\u02B0/', note: 'Lengthened nasal, breathy release' },
    ],
    dialectNotes: 'Undead speech is defined by absence \u2014 the absence of warmth, breath rhythm, and natural prosody. The voice sounds like it is coming from somewhere behind the speaker, hollow and resonant in the wrong frequencies. The key performance challenge is the unnatural pause placement: break sentences where a living person never would. This creates the unsettling feeling that speech is being reconstructed from fragments of memory.',
    vocalParams: { pitch: 3, pacing: 2, resonance: 6, breathiness: 9, gravel: 6 },
    phrases: [
      'I was... a scholar once. Books were my... companions. Now they are my... sustenance.',
      'You fear death. How... quaint. I have been there. It is... overrated.',
      'The living burn so brightly. And so... briefly.',
      'Do not pity me. Pity is for those who still... feel.',
      'I have forgotten my name. I have not forgotten my purpose.',
      'Your heartbeat is... very loud. I had forgotten that sound.',
      'Eternity is not a gift. It is a sentence. I serve it... patiently.',
      'The darkness does not frighten me. The darkness... is where I live.',
    ],
    tips: [
      'Practice the stage whisper: push air through a narrow throat opening, projecting without volume',
      'Break your natural breathing rhythm \u2014 pause where it feels wrong, continue where you would normally stop',
      'Flatten your vocal range to near-monotone, then allow one word per sentence to spike in intensity',
    ],
    rhythm: 'Broken and arrhythmic. Sentences fracture in unexpected places. Long silences that feel intentional and menacing. The rhythm of something that no longer breathes but still speaks.',
    anchorVowel: 'The hollowed /\u025B\u02D0/ as in "death," "end," "dread" \u2014 open but empty, like an echo in a crypt',
    cadenceCheat: 'Speak like you are remembering how to use a mouth and getting it mostly right but not quite.',
    npcArchetypes: ['Lich king or undead sovereign', 'Revenant with unfinished business', 'Ghost bound to a location or object'],
    emotionalRange: ['Hollow detachment', 'Creeping menace', 'Unexpected, heartbreaking nostalgia'],
  },

  // =====================================================================
  // REAL-WORLD INSPIRED ACCENTS (11-24)
  // =====================================================================
  {
    id: 'scottish',
    name: 'Scottish Highland',
    description: 'Warm, rolling Rs with a strong lilt. Broader and more musical than the Dwarven fantasy version.',
    category: 'real-world',
    region: 'Scottish Highlands',
    difficulty: 3,
    tags: ['rolling-r', 'warm', 'lilting', 'musical', 'highland'],
    rules: [
      { rule: 'Roll Rs consistently \u2014 alveolar trill on stressed syllables', example: '"A brright morrrning in the Highlands"' },
      { rule: 'Use the Scottish vowel length rule: vowels shorter before voiceless consonants', example: '"Bite" has a shorter vowel than "bide"' },
      { rule: '"oo" sounds shift toward a fronted /\u0289/', example: '"Good" sounds closer to "guid," "food" to "fuid"' },
      { rule: 'Maintain the /x/ sound (loch, nicht) \u2014 velar fricative', example: '"Loch" with a back-of-throat rasp, never "lock"' },
      { rule: 'Use Scottish vocabulary naturally: "wee," "braw," "ken," "aye"', example: '"That\'s a braw wee blade ye\'ve got there"' },
      { rule: '"ow" sounds stay as /u\u02D0/ rather than diphthongizing', example: '"House" stays as "hoose," "about" as "aboot"' },
    ],
    eyeDialect: [
      { original: 'I do not know about that', accented: "I dinnae ken aboot that", note: '"dinnae" for "don\'t," "ken" for "know," "aboot" for "about"' },
      { original: 'a small beautiful sword', accented: 'a wee braw blade', note: 'Scottish vocabulary substitution' },
      { original: 'It is a good night', accented: "It's a guid nicht", note: 'Fronted OO, velar fricative in "nicht"' },
      { original: 'Go away from here', accented: "Away wi' ye, get yersel' hence", note: 'Reflexive pronoun, Scottish phrasing' },
    ],
    ipa: [
      { word: 'loch', standard: '/l\u0252k/', accented: '/l\u0254x/', note: 'Velar fricative /x/ not present in most English dialects' },
      { word: 'house', standard: '/ha\u028As/', accented: '/hu\u02D0s/', note: 'No diphthong \u2014 stays monophthong /u\u02D0/' },
      { word: 'good', standard: '/\u0261\u028Ad/', accented: '/\u0261\u0289d/', note: 'Fronted /\u0289/ vowel' },
    ],
    dialectNotes: 'Scottish Highland English has a distinctive musicality driven by Gaelic substrate influence. The intonation rises at the end of statements in a way that can sound interrogative to non-Scots. The rhythm alternates between rapid, clipped delivery on unstressed syllables and elongated, musical stressed syllables. The rolled R and velar fricative are the two most distinctive sound features.',
    vocalParams: { pitch: 5, pacing: 5, resonance: 7, breathiness: 2, gravel: 4 },
    phrases: [
      "Aye, I ken these hills like the back of me hand. Every stone's got a story.",
      "Ye dinnae cross a Highlander and walk away smilin'. Remember that.",
      "It's a braw day for a fight, and an even better one for a drink after.",
      'The clans have long memories. We forgive slowly and forget never.',
      "There's a chill in the air tonight. Something's comin' over the loch.",
      "I've walked these moors since I was a wee lad. They've nae changed. I have.",
      "Dinnae fash yersel' \u2014 we'll sort it out, one way or another.",
      "The pipes are callin'. When the pipes call, ye answer. Always.",
    ],
    tips: [
      'Place your tongue tip just behind your upper teeth for the rolled R \u2014 practice with "drrr" and "trrr" combinations',
      'For the /x/ in "loch," raise the back of your tongue toward your soft palate and push air through the gap',
      'Let your intonation rise slightly at the end of declarative sentences \u2014 this is the natural Scottish lilt',
    ],
    rhythm: 'Musical with a lilting rise-fall pattern. Rapid on unstressed syllables, lingering on stressed ones. The Gaelic influence creates a wave-like cadence that distinguishes it from other English dialects.',
    anchorVowel: 'The fronted /\u0289/ in "good," "food," "moon" \u2014 lips rounded but tongue pushed forward',
    cadenceCheat: 'Speak as if every sentence is part of a story being told by a campfire in the Highlands.',
    npcArchetypes: ['Highland warrior or clan chief', 'Village healer or wise woman', 'Traveling bard with ancient songs'],
    emotionalRange: ['Fierce loyalty', 'Warm hospitality', 'Melancholy longing'],
  },
  {
    id: 'irish',
    name: 'Irish (Southern)',
    description: 'Musical, warm, with a distinctive lilt that turns every statement into a near-melody. The rhythm of conversation as art form.',
    category: 'real-world',
    region: 'Southern Ireland (Cork, Kerry)',
    difficulty: 3,
    tags: ['musical', 'warm', 'lilting', 'storytelling', 'charming'],
    rules: [
      { rule: 'TH sounds become T or D: "th" voiced = "d," "th" unvoiced = "t"', example: '"Tink" for "think," "dere" for "there," "tirty-tree" for "thirty-three"' },
      { rule: 'Rising intonation at phrase ends \u2014 more pronounced than Scottish', example: 'Statements lilt upward as if always inviting response' },
      { rule: 'Soften and lighten R sounds \u2014 present but gentle, not rolled hard', example: 'R is tapped, not trilled; lighter than Scottish' },
      { rule: 'Use "after" + gerund for recent past', example: '"I\'m after losing me keys" = "I just lost my keys"' },
      { rule: 'Add Irish English expressions: "grand," "fierce," "yer man," "sure look"', example: '"Ah sure look, it\'ll be grand" = "It will be fine"' },
      { rule: 'Elongate vowels musically on emotionally charged words', example: '"Ah, that\'s looovely" \u2014 the vowel stretches with warmth' },
    ],
    eyeDialect: [
      { original: 'I think there are thirty-three', accented: "I tink dere's tirty-tree", note: 'TH-stopping throughout' },
      { original: 'I just lost my wallet', accented: "I'm after losin' me wallet", note: '"after" + gerund construction' },
      { original: 'It will be fine', accented: "Ah sure look, it'll be grand", note: 'Irish discourse markers' },
      { original: 'That man over there', accented: "Yer man over dere", note: '"Yer man" = that person (known)' },
    ],
    ipa: [
      { word: 'think', standard: '/\u03B8\u026A\u014Bk/', accented: '/t\u026A\u014Bk/', note: 'TH-stopping: /\u03B8/ becomes /t/' },
      { word: 'there', standard: '/\u00F0\u025B\u0259/', accented: '/d\u025B\u0259/', note: 'TH-stopping: /\u00F0/ becomes /d/' },
      { word: 'film', standard: '/f\u026Alm/', accented: '/f\u026Al\u0259m/', note: 'Epenthetic schwa in consonant clusters' },
    ],
    dialectNotes: 'Southern Irish English has perhaps the most musical intonation of any English dialect. The rhythm is driven by stress-timing inherited from Irish Gaelic, creating a characteristic "bounce" where unstressed syllables compress and stressed syllables expand. The TH-stopping is universal but should feel natural, not forced. The warmth comes from the vowel elongation on emotional words and the rising cadence that invites connection.',
    vocalParams: { pitch: 6, pacing: 5, resonance: 5, breathiness: 3, gravel: 2 },
    phrases: [
      "Ah sure, sit down and I'll tell ye a story. It's a good one, I promise.",
      "Fierce weather we're havin'. But sure, when is it not?",
      "Yer man over dere tinks he's clever. He's not wrong, but he's not right either.",
      "I'm after walkin' tree days through rain, and I'd do it again for a pint at the end.",
      "The ting about monsters is, dey're just lonely, most of 'em. Not all. But most.",
      "Grand, grand, everything's grand. Well, it's not, but sayin' it helps.",
      "There's magic in dis land, so dere is. You just have to know where to look.",
      "Me grandmother used to say: never trust a man who doesn't like music. She was right.",
    ],
    tips: [
      'Think of your sentences as gentle hills \u2014 the intonation rises and falls in smooth waves, never sharply',
      'For TH-stopping, place your tongue against your teeth (not between them) and produce a clean T or D',
      'Let warmth and humor come through naturally \u2014 Irish English is a social accent, meant for connection',
    ],
    rhythm: 'Bouncing and musical, like a jig. Unstressed syllables compress while stressed ones stretch. Every sentence has a melodic shape that invites the listener to respond. The rhythm is social and communal.',
    anchorVowel: 'The open /a\u026A/ diphthong as in "my," "night," "time" \u2014 wider and warmer than standard, almost /\u0254\u026A/',
    cadenceCheat: "Speak as if every sentence is the middle of a story you're delighted to be telling.",
    npcArchetypes: ['Charming bard or storyteller', 'Wise village priest or healer', 'Warm innkeeper with secrets'],
    emotionalRange: ['Infectious warmth', 'Gentle melancholy', 'Sharp, understated wit'],
  },
  {
    id: 'cockney',
    name: 'Cockney (East London)',
    description: 'Sharp, fast, and resourceful. The accent of the streets \u2014 H-dropping, glottal stops, and rhyming slang.',
    category: 'real-world',
    region: 'East London',
    difficulty: 3,
    tags: ['street', 'sharp', 'fast', 'h-dropping', 'glottal'],
    rules: [
      { rule: 'Drop H sounds at word beginnings consistently', example: '"\'ello, \'ow are ya? \'aven\'t seen ya in ages"' },
      { rule: 'Replace T with glottal stops between vowels and at word ends', example: '"Bo\'le of wa\'er" for "bottle of water"' },
      { rule: 'TH-fronting: voiceless TH becomes F, voiced TH becomes V', example: '"Fank you bruvver" for "Thank you brother"' },
      { rule: 'The PRICE vowel /a\u026A/ shifts toward /\u0254\u026A/', example: '"Roight" for "right," "noight" for "night"' },
      { rule: 'L-vocalization: dark L becomes a vowel /w/ or /\u028A/', example: '"Miw\u02B7k" for "milk," "beww" for "bell"' },
      { rule: 'Use Cockney expressions and occasional rhyming slang', example: '"Use your loaf" (loaf of bread = head), "have a butcher\'s" (butcher\'s hook = look)' },
    ],
    eyeDialect: [
      { original: 'hello, how are you?', accented: "'ello, 'ow are ya?", note: 'H-dropping, informal "ya"' },
      { original: 'I think that is right', accented: "I fink that's roight", note: 'TH-fronting, PRICE vowel shift' },
      { original: 'bottle of milk', accented: "bo'le of miwk", note: 'Glottal stop, L-vocalization' },
      { original: 'Look at that, brother', accented: "'Ave a butcher's at that, bruvver", note: 'Rhyming slang, TH-fronting' },
    ],
    ipa: [
      { word: 'right', standard: '/\u0279a\u026At/', accented: '/\u0279\u0254\u026At/', note: 'PRICE vowel backed to /\u0254\u026A/' },
      { word: 'milk', standard: '/m\u026Alk/', accented: '/m\u026A\u028Ak/', note: 'L-vocalization to /\u028A/' },
      { word: 'think', standard: '/\u03B8\u026A\u014Bk/', accented: '/f\u026A\u014Bk/', note: 'TH-fronting' },
    ],
    dialectNotes: 'Cockney is the working-class accent of East London, characterized by a rapid delivery that reflects street smarts and quick wit. The accent is socially performative \u2014 it signals in-group belonging and resourcefulness. The key features (H-dropping, glottal stops, TH-fronting) should flow naturally together rather than being applied individually. Rhyming slang should be used sparingly and for flavor, not overdone.',
    vocalParams: { pitch: 6, pacing: 8, resonance: 4, breathiness: 2, gravel: 3 },
    phrases: [
      "Right, 'ere's the fing \u2014 I ain't got all day, so make it quick.",
      "You fink you're clever? I've forgotten more tricks than you've ever learned.",
      "Nah, nah, nah. That ain't 'ow it works round 'ere, mate.",
      "I grew up on these streets. Every alley, every rooftop. This is MY manor.",
      "Fancy a cuppa? No? Suit yourself. More for me, innit.",
      "See, the fing about trust is, ya gotta earn it. And earnin' it takes time.",
      "I ain't scared of nuffink. Well, maybe spiders. But nuffink else.",
      "Money talks, bruvver. And right now, yours ain't saying much.",
    ],
    tips: [
      'Practice the glottal stop by saying "uh-oh" repeatedly \u2014 that catch in your throat replaces T in most positions',
      'TH-fronting should feel effortless: just place your tongue on your teeth (not between) and say F or V',
      'Speed matters \u2014 Cockney is a fast accent; slow Cockney sounds wrong',
    ],
    rhythm: 'Rapid-fire with rhythmic emphasis. Sentences tumble out quickly with punchy stress on key words. The rhythm is percussive and urban \u2014 clipped, confident, and never dragging.',
    anchorVowel: 'The backed /\u0254\u026A/ in "right," "night," "my" \u2014 this single vowel shift is the most recognizable Cockney marker',
    cadenceCheat: "Speak like you're haggling at a market stall and you've got three other customers waiting.",
    npcArchetypes: ['Street-smart rogue or informant', 'Market vendor with questionable goods', 'Retired adventurer running a tavern'],
    emotionalRange: ['Quick-witted banter', 'Tough-love loyalty', 'Street-hardened defiance'],
  },
  {
    id: 'rp-english',
    name: 'RP English (Received Pronunciation)',
    description: 'The standard prestige accent of England. Clear, precise, and carrying understated authority without the aristocratic affectation of the Noble variant.',
    category: 'real-world',
    region: 'England (prestige standard)',
    difficulty: 2,
    tags: ['clear', 'precise', 'prestige', 'standard', 'understated'],
    rules: [
      { rule: 'Non-rhotic: never pronounce R after a vowel', example: '"Car" is "cah," "water" is "watah," "here" is "heeah"' },
      { rule: 'BATH-broadening: /\u00E6/ becomes /\u0251\u02D0/ in specific words', example: '"Bahth," "grahss," "chahns" \u2014 but "cat" stays "cat"' },
      { rule: 'Clear, aspirated T sounds in all positions', example: '"BeTTer," "waTer," "righT" \u2014 never dropped or glottalized' },
      { rule: 'GOAT vowel as /\u0259\u028A/ \u2014 centralized diphthong', example: '"Go" is /\u0261\u0259\u028A/, not /\u0261o\u028A/ \u2014 the first element is a schwa' },
      { rule: 'Maintain even, measured pacing without affectation', example: 'Clear and composed, not performatively posh' },
      { rule: 'Use linking and intrusive R between vowels', example: '"Law-r-and order," "India-r-and China"' },
    ],
    eyeDialect: [
      { original: 'the car is far', accented: 'the cah is fah', note: 'Non-rhotic throughout' },
      { original: 'a glass of water', accented: 'a glahss of watah', note: 'BATH-broadening, non-rhotic' },
      { original: 'better', accented: 'bet-tah', note: 'Clear T, non-rhotic final' },
      { original: 'going home', accented: "geu-ing heume", note: 'Centralized GOAT diphthong' },
    ],
    ipa: [
      { word: 'bath', standard: '/b\u00E6\u03B8/', accented: '/b\u0251\u02D0\u03B8/', note: 'BATH-broadening' },
      { word: 'go', standard: '/\u0261o\u028A/', accented: '/\u0261\u0259\u028A/', note: 'Centralized GOAT vowel' },
      { word: 'car', standard: '/k\u0251\u02D0\u0279/', accented: '/k\u0251\u02D0/', note: 'Non-rhotic, no final R' },
    ],
    dialectNotes: 'RP is the prestige standard of British English, used by newsreaders and in formal contexts. Unlike the Noble fantasy accent, RP does not inherently carry condescension \u2014 it is simply clear, precise, and neutral. The key is controlled delivery without affectation. Modern RP has moved away from the ultra-posh "Queen\'s English" toward a more accessible, educated standard.',
    vocalParams: { pitch: 5, pacing: 4, resonance: 5, breathiness: 2, gravel: 1 },
    phrases: [
      "I rather think we should consider all the options before proceeding.",
      "It's quite straightforward, really. One simply needs to pay attention.",
      "The weather has been perfectly dreadful, hasn't it? Still, mustn't grumble.",
      "I've seen worse situations, and I've managed. This is no different.",
      "If you'll forgive me for saying so, that plan has some significant flaws.",
      "Shall we get on with it, then? Time is rather pressing.",
      "I don't mean to be difficult, but the facts simply don't support that conclusion.",
      "A cup of tea would sort this out nicely. It usually does.",
    ],
    tips: [
      'Focus on the non-rhotic R first \u2014 practice saying "car," "far," "water" without any R sound at the end',
      'Keep your jaw relaxed but not slack \u2014 RP is precise without being tense',
      'The BATH-broadening only applies to a specific set of words; "cat," "hat," and "bat" keep the short /\u00E6/',
    ],
    rhythm: 'Even, measured, and clear. Neither rushed nor dragging. The rhythm signals composure and education without ostentation. Every syllable is given its due weight.',
    anchorVowel: 'The broad /\u0251\u02D0/ in BATH words \u2014 "glass," "bath," "chance" \u2014 jaw open, tongue low and back',
    cadenceCheat: 'Speak like a BBC newsreader from the 1990s \u2014 clear, composed, and trustworthy.',
    npcArchetypes: ['Scholar or university professor', 'Diplomat or negotiator', 'Composed military officer'],
    emotionalRange: ['Calm authority', 'Understated concern', 'Dry, gentle humor'],
  },
  {
    id: 'french',
    name: 'French-Accented English',
    description: 'Melodic, with a distinctive rhythm driven by syllable-timing, uvular R, and a refusal to stress individual syllables the way English demands.',
    category: 'real-world',
    region: 'France',
    difficulty: 2,
    tags: ['melodic', 'syllable-timed', 'romantic', 'uvular-r', 'nasal'],
    rules: [
      { rule: 'Use syllable-timing instead of stress-timing: every syllable gets roughly equal length', example: '"In-ter-est-ing" with even weight, not "IN-trest-ing"' },
      { rule: 'Replace the English R with a uvular R /\u0281/', example: 'The R is produced at the back of the throat, not the front' },
      { rule: 'H is silent \u2014 drop it completely', example: '"\'appy," "\'ere," "\'ow" \u2014 the H simply does not exist' },
      { rule: 'TH sounds become Z or S', example: '"Zis" for "this," "ze" for "the," "sink" for "think"' },
      { rule: 'Stress the final syllable of multi-syllable words', example: '"po-LICE," "in-ter-est-ING," "beau-ti-FUL"' },
      { rule: 'Add nasal quality to vowels before N and M', example: '"Interestang" \u2014 the final vowel nasalizes' },
    ],
    eyeDialect: [
      { original: 'I think this is very interesting', accented: "I sink zis is veh-ry inteh-rest-ING", note: 'TH-to-Z/S, syllable-timing, final stress' },
      { original: 'Happy to help', accented: "'Appy to 'elp", note: 'H-dropping' },
      { original: 'The weather here', accented: "Ze wez-AIR 'ere", note: 'TH to Z, final stress, H-drop' },
      { original: 'It does not matter', accented: "Eet does not mat-TAIR", note: 'Final-syllable stress' },
    ],
    ipa: [
      { word: 'this', standard: '/\u00F0\u026As/', accented: '/z\u026As/', note: 'TH-to-Z replacement' },
      { word: 'interesting', standard: '/\u02C8\u026Ant\u0279\u0259st\u026A\u014B/', accented: '/\u025B\u0303.te.\u0281\u025Bs.t\u026A\u014B/', note: 'Syllable-timed, uvular R, nasal vowel' },
      { word: 'happy', standard: '/\u02C8h\u00E6pi/', accented: '/a.pi/', note: 'H-dropped, open A' },
    ],
    dialectNotes: 'French-accented English is driven by the fundamental difference between French syllable-timing and English stress-timing. English speakers emphasize certain syllables and swallow others; French speakers give each syllable nearly equal weight, creating a distinctive even rhythm. This, combined with the uvular R and H-dropping, produces the immediately recognizable "French accent." The key is musicality without mockery.',
    vocalParams: { pitch: 6, pacing: 4, resonance: 4, breathiness: 4, gravel: 2 },
    phrases: [
      "Zis dungeon, it is... 'ow you say... absolutely disgusting. But ze treasure, it calls to me.",
      "I do not run from danger. I simply choose to face it at a more convenient time.",
      "Ze food 'ere is terrible. In my country, even ze peasants eat better zan zis.",
      "Love is ze most powerful magic. Also ze most dangerous. I speak from experience.",
      "You want my 'elp? Very well. But first, we negotiate ze terms.",
      "I 'ave seen beautiful sings in my travels. Zis is not one of zem. But it 'as... potential.",
      "Courage is not ze absence of fear. It is 'aving fear and ordering anozzer glass of wine.",
      "Ze plan is simple. Ze execution... zat is where it becomes inteh-rest-ING.",
    ],
    tips: [
      'For the uvular R, gargle gently \u2014 the vibration at the back of your throat is where the French R lives',
      'Practice syllable-timing by tapping a finger for each syllable, keeping them perfectly even',
      'Drop all Hs completely and without hesitation \u2014 in French, H simply does not exist',
    ],
    rhythm: 'Syllable-timed and even, with a gentle musicality. No syllable is swallowed or crushed. The rhythm feels smoother and more measured than English, like each syllable is a step in a dance.',
    anchorVowel: 'The nasalized /\u0251\u0303/ as in French "en," "an" \u2014 applied to English words ending in N: "interestang," "importahnt"',
    cadenceCheat: "Speak as if every sentence is a philosophical observation you're mildly amused to be sharing.",
    npcArchetypes: ['Suave diplomat or spy', 'Romantic duelist or swashbuckler', 'Sophisticated merchant or artisan'],
    emotionalRange: ['Charming persuasion', 'Dismissive elegance', 'Passionate intensity'],
  },
  {
    id: 'german',
    name: 'Germanic English',
    description: 'Precise, structured, with sharp consonants and a methodical delivery. Every sentence is engineered for clarity.',
    category: 'real-world',
    region: 'Germany / Austria',
    difficulty: 3,
    tags: ['precise', 'structured', 'sharp', 'methodical', 'consonant-heavy'],
    rules: [
      { rule: 'W sounds become V: the English /w/ does not exist in German', example: '"Vhat" for "what," "vith" for "with," "vell" for "well"' },
      { rule: 'Final consonant devoicing: voiced stops become voiceless at word ends', example: '"Goot" for "good," "hant" for "hand"' },
      { rule: 'TH sounds become Z or S (voiced) or T/S (voiceless)', example: '"Ze" for "the," "zis" for "this," "sink" for "think"' },
      { rule: 'Harder, more aspirated consonants throughout', example: 'Every P, T, K gets a burst of air: "P-lan," "T-ime," "K-ome"' },
      { rule: 'Verb-final constructions in complex sentences', example: '"This is something that considered must be" \u2014 occasional V2 word order bleed' },
      { rule: 'Short, precise vowels \u2014 less diphthong glide than English', example: '"No" stays tight as /no\u02D0/, not /n\u0259\u028A/' },
    ],
    eyeDialect: [
      { original: 'What do you want with this?', accented: 'Vhat do you vant vith zis?', note: 'W-to-V, TH-to-Z throughout' },
      { original: 'That is good', accented: 'Zat is goot', note: 'TH-to-Z, final devoicing' },
      { original: 'We will find a way', accented: 'Ve vill find a vay', note: 'W-to-V consistently' },
      { original: 'This must be done carefully', accented: 'Zis must carefully done be', note: 'Verb-final word order' },
    ],
    ipa: [
      { word: 'what', standard: '/w\u0252t/', accented: '/v\u0252t/', note: '/w/ replaced by /v/' },
      { word: 'good', standard: '/\u0261\u028Ad/', accented: '/\u0261\u028At/', note: 'Final devoicing /d/ to /t/' },
      { word: 'the', standard: '/\u00F0\u0259/', accented: '/z\u0259/', note: 'TH-to-Z' },
    ],
    dialectNotes: 'Germanic English is characterized by precision and structure. The German phonological system maps onto English in predictable ways: W-to-V, TH-to-Z/S, final devoicing. The rhythm is more syllable-timed than English, with each word given clear articulation. The cultural overlay is methodical and direct \u2014 German speakers tend toward clarity over ambiguity, which translates to direct, efficient sentence construction.',
    vocalParams: { pitch: 4, pacing: 4, resonance: 6, breathiness: 1, gravel: 3 },
    phrases: [
      'Zis plan, it has structure. I approve. Ve proceed.',
      'Vhat you call chaos, I call a problem zat has not yet been properly organized.',
      'Ze sword is goot. Ze technique is... ve vill vork on ze technique.',
      'I do not guess. I calculate. Ze difference is important.',
      'Efficiency is not cold. Efficiency is respect for time.',
      'You vant to know if I am afraid? Fear is irrelevant. Preparation is vhat matters.',
      'Ze instructions vere clear. You simply did not follow zem.',
      'In my country, ve have a saying: measure twice, cut once. You did not measure at all.',
    ],
    tips: [
      'For the W-to-V shift, press your upper teeth against your lower lip for every W sound',
      'Practice final devoicing by saying "good-goot," "hand-hant," "bad-bat" in pairs',
      'Keep your consonants crisp and aspirated \u2014 German articulation is more muscular than English',
    ],
    rhythm: 'Measured and precise, with clear word boundaries. Each syllable is articulated distinctly. The rhythm is more even than English, reflecting Germanic syllable-timing. Sentences feel structured and intentional.',
    anchorVowel: 'The tight /o\u02D0/ in words like "no," "go," "so" \u2014 kept as a pure monophthong, no diphthong glide',
    cadenceCheat: 'Speak as if you are giving technical instructions that must be followed exactly.',
    npcArchetypes: ['Military strategist or commander', 'Precise artificer or engineer', 'Stern but fair instructor'],
    emotionalRange: ['Controlled determination', 'Dry, understated humor', 'Intense focused passion'],
  },
  {
    id: 'russian',
    name: 'Russian/Slavic English',
    description: 'Strong, direct, with dark vowels and a no-nonsense delivery. Every sentence sounds like it was forged in winter.',
    category: 'real-world',
    region: 'Russia / Eastern Europe',
    difficulty: 3,
    tags: ['strong', 'dark-vowels', 'direct', 'consonant-clusters', 'stoic'],
    rules: [
      { rule: 'Drop articles ("a," "an," "the") \u2014 Russian has none', example: '"Give me sword" not "Give me the sword"' },
      { rule: 'W becomes V throughout', example: '"Ve vill do vhat must be done"' },
      { rule: 'TH becomes Z or D (voiced) or S or T (voiceless)', example: '"Ze" or "de" for "the," "sink" for "think"' },
      { rule: 'Dark, backed vowels \u2014 /\u00E6/ becomes /\u025B/ or /a/', example: '"Bat" sounds closer to "bet" or "baht"' },
      { rule: 'Palatalized consonants before front vowels', example: 'A slight "y" glide before "ee" sounds: "nyeed" for "need"' },
      { rule: 'Blunt, minimal phrasing \u2014 strip sentences to essentials', example: '"Is good" not "That\'s quite good, I think"' },
    ],
    eyeDialect: [
      { original: 'Give me the sword', accented: 'Give me sword', note: 'Article dropping' },
      { original: 'We will do what must be done', accented: 'Ve vill do vhat must be done', note: 'W-to-V shift' },
      { original: 'That is very good', accented: 'Is good. Very good.', note: 'Article dropping, blunt confirmation' },
      { original: 'I think we should leave', accented: 'Ve go. Now.', note: 'Radical simplification' },
    ],
    ipa: [
      { word: 'the', standard: '/\u00F0\u0259/', accented: '/z\u0259/', note: 'TH-to-Z' },
      { word: 'what', standard: '/w\u0252t/', accented: '/v\u0254t/', note: 'W-to-V, backed vowel' },
      { word: 'need', standard: '/ni\u02D0d/', accented: '/n\u02B2i\u02D0t/', note: 'Palatalized N, final devoicing' },
    ],
    dialectNotes: 'Russian English is defined by subtraction as much as substitution. Articles vanish, syllables compress, and sentences reduce to their load-bearing elements. The dark vowel quality gives everything a weighted, serious feel. The palatalization before front vowels adds a subtle softness that contrasts with the overall directness. The accent communicates pragmatism and endurance \u2014 people who speak this way have survived things.',
    vocalParams: { pitch: 3, pacing: 4, resonance: 8, breathiness: 1, gravel: 5 },
    phrases: [
      'Is simple. Ve go in, ve fight, ve come out. Maybe ve come out.',
      'Trust is earned vith blood, not vords. Show me.',
      'In my country, vinter teaches you or kills you. I am still here.',
      'You talk too much. Action speaks. Vords are... vind.',
      'I have seen vorse. Much vorse. Zis? Zis is Tuesday.',
      'Pain is old friend. Ve have understanding, pain and I.',
      'You vant to know my story? Buy me drink first. Good drink. Not zis.',
      'Zere is saying: hope for best, prepare for vorst. I alvays prepare for vorst.',
    ],
    tips: [
      'Practice dropping all articles from your sentences \u2014 "give me sword," "open door," "light is fading"',
      'Back your vowels by pulling your tongue slightly toward the rear of your mouth',
      'Keep your delivery flat and matter-of-fact \u2014 emotional restraint is the performance style',
    ],
    rhythm: 'Direct and weight-bearing. Sentences are short and land heavily. The rhythm strips away filler, leaving only essential syllables. Pauses are not dramatic \u2014 they are simply where the thought ends.',
    anchorVowel: 'The dark /\u0254/ in words like "what," "not," "god" \u2014 backed, rounded, and heavy',
    cadenceCheat: 'Speak as if words cost money and you are on a budget.',
    npcArchetypes: ['Hardened mercenary or soldier', 'Stoic blacksmith or craftsman', 'Weary but wise traveler'],
    emotionalRange: ['Stoic resolve', 'Dry, dark humor', 'Fierce protective loyalty'],
  },
  {
    id: 'nordic',
    name: 'Nordic (Scandinavian)',
    description: 'Musical, with a distinctive pitch-accent and sing-song quality. Clear consonants, rounded vowels, and an understated warmth.',
    category: 'real-world',
    region: 'Scandinavia (Sweden, Norway, Denmark)',
    difficulty: 2,
    tags: ['musical', 'pitch-accent', 'clear', 'rounded', 'understated'],
    rules: [
      { rule: 'Apply pitch-accent: stressed syllables get a tonal rise-fall pattern', example: 'Words have a musical "bounce" on stressed syllables, almost sung' },
      { rule: 'J sound replaces Y in some positions', example: '"Yes" can sound closer to "Jes," with a slightly harder onset' },
      { rule: 'Rounded front vowels: the /y/ and /\u00F8/ sounds of Scandinavian bleed through', example: '"You" with more lip rounding, "bird" with a rounded /\u00F8/' },
      { rule: 'Clean, clear consonants with minimal reduction', example: 'Every consonant is pronounced; nothing swallowed' },
      { rule: 'Relatively flat intonation with the pitch-accent bounce as the main melody', example: 'Not as dramatically rising as Irish; more controlled musicality' },
      { rule: 'Understatement in phrasing \u2014 less is more', example: '"That is... not ideal" for a catastrophe' },
    ],
    eyeDialect: [
      { original: 'Yes, that is very good', accented: 'Ja, zat is very good', note: '"Ja" for "yes," slight TH-to-Z' },
      { original: 'I think we should go', accented: 'I tink ve should go, ja?', note: 'TH-to-T, tag question with "ja"' },
      { original: 'It is not that bad', accented: 'It is not so bad. Could be vorse.', note: 'Understatement pattern' },
      { original: 'That is a problem', accented: 'Zat is... not ideal', note: 'Scandinavian understatement' },
    ],
    ipa: [
      { word: 'yes', standard: '/j\u025Bs/', accented: '/j\u025As/', note: 'Slightly more closed vowel' },
      { word: 'the', standard: '/\u00F0\u0259/', accented: '/d\u0259/', note: 'TH-stopping (dental D)' },
      { word: 'bird', standard: '/b\u025C\u02D0d/', accented: '/b\u00F8\u02D0d/', note: 'Rounded front vowel' },
    ],
    dialectNotes: 'Scandinavian English is immediately identifiable by its pitch-accent \u2014 the musical "bounce" on stressed syllables that gives it a sing-song quality. The accent is generally very clear and easy to understand, with clean consonant articulation. The cultural overlay is one of understated competence: Nordic speakers tend toward pragmatic directness without aggression, and dramatic understatement.',
    vocalParams: { pitch: 5, pacing: 4, resonance: 5, breathiness: 2, gravel: 2 },
    phrases: [
      'Ja, I have seen bigger monsters. This is... medium-sized. Ve can handle it.',
      'The cold does not bozer me. I grew up vith it. It is like an old friend. A terrible friend.',
      'I do not boast. I simply state facts. And ze fact is, I am very good at this.',
      'Zere is a saying in my country: ze quietest person at ze table is usually ze most dangerous.',
      'Teamvork is important. I vill do my part. You vill do yours. It is simple.',
      "I am not angry. I am... disappointed. Zat is vorse, ja?",
      'Ze sea teaches you patience. And if it does not teach you, it drowns you. Very efficient.',
      'You ask if I am afraid. Fear is useful. It keeps you sharp. So ja, I am afraid. And I am ready.',
    ],
    tips: [
      'Practice the pitch-accent bounce by exaggerating the musical rise on stressed syllables, then dial it back to 50%',
      'Round your lips more than feels natural on front vowels \u2014 this creates the distinctive Scandinavian vowel color',
      'Speak with calm, even energy \u2014 Nordic delivery is warm but never overwrought',
    ],
    rhythm: 'Sing-song with a controlled pitch-accent bounce. The melody is subtle and regular, creating a pleasant, musical quality. Pacing is moderate and even, with clear word boundaries.',
    anchorVowel: 'The rounded front /\u00F8/ in words like "bird," "turn," "learn" \u2014 round your lips while making an "eh" sound',
    cadenceCheat: 'Speak as if you are calmly describing something remarkable while not being particularly impressed by it.',
    npcArchetypes: ['Seafaring navigator or captain', 'Calm, competent ranger or scout', 'Understated sage or runecarver'],
    emotionalRange: ['Quiet competence', 'Understated warmth', 'Steely determination'],
  },
  {
    id: 'appalachian',
    name: 'Appalachian',
    description: 'Ancient, lilting, with roots in Scots-Irish and Elizabethan English. Proud, musical, and deeply connected to the land.',
    category: 'real-world',
    region: 'Appalachian Mountains (Eastern US)',
    difficulty: 3,
    tags: ['lilting', 'archaic', 'rural', 'scots-irish', 'proud'],
    rules: [
      { rule: 'A-prefixing: add "a-" before present participles', example: '"He went a-runnin\' down the holler"' },
      { rule: 'Use archaic verb forms that survive from Elizabethan English', example: '"I might could do that," "used to could," "fixin\' to"' },
      { rule: 'Pronounce the "r" strongly in all positions (fully rhotic)', example: '"Warsh" for wash (intrusive R), "far" with strong final R' },
      { rule: 'Diphthong smoothing: /a\u026A/ becomes /a\u02D0/ before voiced consonants', example: '"Tahm" for "time," "rahd" for "ride"' },
      { rule: 'Use "yonder" for distance, "directly" for soon, "reckon" for think', example: '"I reckon he\'s over yonder. He\'ll be back directly."' },
      { rule: 'Double modals in complex constructions', example: '"You might ought to be careful" = "You should probably be careful"' },
    ],
    eyeDialect: [
      { original: 'He was running down the hollow', accented: "He went a-runnin' down the holler", note: 'A-prefixing, "hollow" to "holler"' },
      { original: 'I think he is over there', accented: "I reckon he's over yonder", note: '"reckon" and "yonder"' },
      { original: 'I used to be able to do that', accented: 'I used to could do that', note: 'Double modal construction' },
      { original: 'We are going to fix this', accented: "We're fixin' to sort this out", note: '"fixin\' to" for imminent future' },
    ],
    ipa: [
      { word: 'time', standard: '/ta\u026Am/', accented: '/ta\u02D0m/', note: 'Diphthong smoothing before voiced consonant' },
      { word: 'fire', standard: '/fa\u026A\u0259/', accented: '/fa\u02D0\u0279/', note: 'Smoothed diphthong, strong R' },
      { word: 'wash', standard: '/w\u0252\u0283/', accented: '/w\u0254\u0279\u0283/', note: 'Intrusive R' },
    ],
    dialectNotes: 'Appalachian English preserves linguistic features from Scots-Irish and Elizabethan English that have vanished from other American dialects. The double modals, a-prefixing, and archaic vocabulary are not "incorrect" English \u2014 they are older English, carried into the mountains and preserved. The accent is proud and musical, with a lilting quality that reflects its Scots-Irish heritage.',
    vocalParams: { pitch: 5, pacing: 4, resonance: 6, breathiness: 3, gravel: 4 },
    phrases: [
      "I reckon that critter ain't natural. Best keep your distance till we figure it out.",
      "My grandaddy used to could tell weather by the way the leaves turned. I'm a-learnin' the same.",
      "You might ought to watch your step around here. These hills got teeth.",
      "Ain't no shame in bein' scared. Shame's in lettin' it stop you.",
      "Been a-walkin' these ridges since I was knee-high. Every rock's got a story.",
      "We don't got much, but what we got, we share. That's mountain law.",
      "The old songs carry more truth than any book I ever read.",
      "Fixin' to storm. Feel it in my bones. We best find shelter directly.",
    ],
    tips: [
      'Practice a-prefixing by adding "a-" before any -ing word: "a-runnin\'," "a-comin\'," "a-thinkin\'"',
      'The diphthong smoothing is subtle: "time" does not become "tom" \u2014 it becomes "tahm," with the vowel slightly open',
      'Keep the delivery warm and grounded \u2014 this is a proud accent, not a comedic one',
    ],
    rhythm: 'Lilting and musical with Scots-Irish roots. The rhythm has a gentle rise-fall that feels like walking through rolling hills. Pacing is moderate, with room for contemplation.',
    anchorVowel: 'The smoothed /a\u02D0/ in "time," "ride," "night" \u2014 the diphthong relaxes to a simple long vowel',
    cadenceCheat: "Speak as if you're on a porch, watching the sunset, and you've got all evening to tell the story.",
    npcArchetypes: ['Mountain hermit or herbalist', 'Frontier guide or tracker', 'Folk healer or hedge witch'],
    emotionalRange: ['Quiet pride', 'Warm hospitality', 'Fierce independence'],
  },
  {
    id: 'texan',
    name: 'Texan/Deep South',
    description: 'Warm, drawling, and expansive. Vowels stretch like the open plains. A voice that takes its time because it owns the room.',
    category: 'real-world',
    region: 'Texas / American Deep South',
    difficulty: 2,
    tags: ['drawling', 'warm', 'expansive', 'slow', 'hospitable'],
    rules: [
      { rule: 'Drawl on stressed vowels \u2014 stretch them to nearly twice their length', example: '"Weeell now" for "Well now," "Hooow about that"' },
      { rule: 'Monophthongize /a\u026A/ to /a\u02D0/ (pin-pen merger territory)', example: '"Ah" for "I," "mahnd" for "mind," "raht" for "right"' },
      { rule: 'Use "y\'all" naturally and "fixin\' to" for imminent action', example: '"Y\'all fixin\' to head out?" = "Are you all about to leave?"' },
      { rule: 'Add "ol\'" as a general intensifier or softener', example: '"That big ol\' dragon," "this nice ol\' tavern"' },
      { rule: 'Slow your pacing by about 25% from conversational speed', example: 'Every sentence should feel unhurried and expansive' },
      { rule: 'Use colorful similes and comparisons', example: '"Hotter than a snake in a wagon rut," "Happier than a clam at high tide"' },
    ],
    eyeDialect: [
      { original: 'I am going to fix this', accented: "Ah'm fixin' to sort this out", note: '"Ah" for "I," fixin\' to' },
      { original: 'That is very large', accented: "Now that's a big ol' sumbitch", note: 'Drawl, "ol\'" softener' },
      { original: 'Are you all ready to go?', accented: "Y'all ready to roll?", note: '"y\'all" as standard second-person plural' },
      { original: 'It is extremely hot', accented: "It's hotter'n two rats in a wool sock", note: 'Colorful simile, contraction' },
    ],
    ipa: [
      { word: 'I', standard: '/a\u026A/', accented: '/a\u02D0/', note: 'Monophthongized, the "Southern Ah"' },
      { word: 'well', standard: '/w\u025Bl/', accented: '/w\u025B\u02D0\u028Al/', note: 'Drawled with breaking' },
      { word: 'right', standard: '/\u0279a\u026At/', accented: '/\u0279a\u02D0t/', note: 'Monophthongized /a\u026A/' },
    ],
    dialectNotes: 'Texan English is the sound of space and time \u2014 the vowels stretch because the landscape stretches. The drawl is not slowness but deliberation; every word gets its full due. The cultural overlay is hospitality and confidence: Texan speakers own the room and make you feel welcome in it. The colorful similes are a genuine feature of the dialect, not affectation.',
    vocalParams: { pitch: 4, pacing: 3, resonance: 7, breathiness: 3, gravel: 4 },
    phrases: [
      "Well now, that's about the ugliest critter Ah've ever laid eyes on. And Ah've seen a lot.",
      "Y'all want to fight that thing? Shoot, Ah was hopin' we could talk it out over some barbecue.",
      "Ah'm not sayin' Ah'm the best shot in the territory. Ah'm just sayin' nobody's proved me wrong yet.",
      "This here dungeon? Ah've seen scarier basements. Let's ride.",
      "There's two kinds of people: those who finish what they start, and those who ain't worth knowin'.",
      "Hotter than a jalape\u00F1o in a cast-iron skillet down here. But we press on.",
      "My daddy always said: if you're gonna be dumb, you gotta be tough. Ah'm both.",
      "Sit down, friend. Tell me your troubles. We got time, and the whiskey's free.",
    ],
    tips: [
      'Practice the drawl by stretching stressed vowels to double their normal length \u2014 "well" becomes "weeeell"',
      'Monophthongize /a\u026A/ to /a\u02D0/: say "my mind is right" as "mah mahnd is raht"',
      'Speak with genuine warmth and confidence \u2014 the Texan accent is generous, not lazy',
    ],
    rhythm: 'Slow, drawling, and expansive. Stressed syllables stretch luxuriously while unstressed ones compress. The rhythm is like a long highway through open country \u2014 no rush, no boundaries, plenty of room.',
    anchorVowel: 'The monophthongal /a\u02D0/ replacing /a\u026A/ \u2014 "I," "my," "right" all become long, open, unhurried vowels',
    cadenceCheat: "Speak like you own everything you can see and you're happy to share it.",
    npcArchetypes: ['Rancher or frontier settler', 'Charismatic sheriff or marshal', 'Larger-than-life merchant prince'],
    emotionalRange: ['Warm hospitality', 'Slow-burning anger', 'Boisterous confidence'],
  },
  {
    id: 'new-york',
    name: 'New York',
    description: 'Fast, assertive, and rhythmic. The accent of people who have somewhere to be and something to say about it.',
    category: 'real-world',
    region: 'New York City',
    difficulty: 3,
    tags: ['fast', 'assertive', 'urban', 'rhythmic', 'direct'],
    rules: [
      { rule: 'Non-rhotic in traditional form: R drops after vowels', example: '"New Yawk," "watah," "cah" \u2014 though younger speakers are more rhotic' },
      { rule: 'THOUGHT vowel is raised and rounded: /\u0254\u02D0/ becomes very open and long', example: '"Cawffee," "tawk," "dawg" \u2014 the vowel is exaggerated' },
      { rule: 'Short A tensing before nasals and voiced stops', example: '"Man" and "bad" get a raised, tense /e\u0259/ diphthong' },
      { rule: 'Speak fast and overlap conversational turns', example: 'Interrupting is not rude; it means you are engaged' },
      { rule: 'Use "you know what I mean?" and similar tag confirmations', example: '"It\'s a whole thing, you know what I\'m sayin\'?"' },
      { rule: 'Emphasis through volume and repetition, not pacing', example: '"I told you. I TOLD you. What did I tell you?"' },
    ],
    eyeDialect: [
      { original: 'coffee', accented: 'cawffee', note: 'Raised THOUGHT vowel' },
      { original: 'I am walking over there', accented: "I'm walkin' ovah deah", note: 'Non-rhotic, g-dropping' },
      { original: 'Forget about it', accented: 'Fuggedaboutit', note: 'Iconic phrase compression' },
      { original: 'That is not right, man', accented: "That ain't right, you know what I mean?", note: 'Tag question, direct delivery' },
    ],
    ipa: [
      { word: 'coffee', standard: '/\u02C8k\u0252fi/', accented: '/\u02C8k\u0254\u02D0fi/', note: 'Raised, lengthened THOUGHT vowel' },
      { word: 'car', standard: '/k\u0251\u02D0\u0279/', accented: '/k\u0251\u02D0/', note: 'Non-rhotic' },
      { word: 'bad', standard: '/b\u00E6d/', accented: '/be\u0259d/', note: 'Short-A tensing and raising' },
    ],
    dialectNotes: 'New York English is the accent of velocity and engagement. Conversations are competitive in a friendly way \u2014 overlapping speech signals interest, not disrespect. The accent is non-rhotic in its classic form, though this is evolving. The raised THOUGHT vowel and short-A tensing are the most distinctive features. The cultural overlay is confidence bordering on combativeness: New Yorkers have opinions and they share them freely.',
    vocalParams: { pitch: 6, pacing: 8, resonance: 5, breathiness: 1, gravel: 4 },
    phrases: [
      "Listen, I've been in worse spots than this, alright? Much worse. This ain't nothin'.",
      "You want my advice? Here's my advice: don't ask for advice. Just do the thing.",
      "Hey, I'm walkin' here! You got a whole dungeon and you gotta stand RIGHT there?",
      "Let me tell you somethin' \u2014 I been in this game a long time. LONG time.",
      "No offense, but your plan stinks. Here's what we're gonna do instead.",
      "I got a guy for that. I got a guy for everything. That's how you survive this city.",
      "You think I'm scared? I grew up on the Lower East Side. Dragons got nothin' on my landlord.",
      "Look, we can stand here talkin' all day, or we can go in there and handle it. Your call.",
    ],
    tips: [
      'Speed is essential \u2014 practice speaking 25-30% faster than comfortable, with confidence',
      'For the raised THOUGHT vowel, open your mouth wider on "aw" sounds and hold them longer',
      'Overlap and interrupt yourself \u2014 New York speech is layered and recursive, not linear',
    ],
    rhythm: 'Fast, assertive, rhythmic. Sentences pile up and overlap. Emphasis comes through volume spikes and repetition. The rhythm is urban and percussive \u2014 like the city itself, always moving.',
    anchorVowel: 'The raised /\u0254\u02D0/ in "coffee," "talk," "all" \u2014 round, open, and held longer than standard',
    cadenceCheat: "Speak like you're telling a friend a story while crossing a busy intersection.",
    npcArchetypes: ['Street-smart fixer or broker', 'Opinionated guild leader', 'Fast-talking con artist with a heart'],
    emotionalRange: ['Intense loyalty', 'Combative affection', 'Rapid-fire problem-solving'],
  },
  {
    id: 'australian',
    name: 'Australian',
    description: 'Relaxed, warm, and laconic. Vowels shift and shorten, sentences rise at the end, and everything sounds like an invitation to not take things too seriously.',
    category: 'real-world',
    region: 'Australia',
    difficulty: 2,
    tags: ['relaxed', 'laconic', 'rising-intonation', 'warm', 'casual'],
    rules: [
      { rule: 'Raise the FACE vowel: /e\u026A/ becomes closer to /\u00E6\u026A/ or even /a\u026A/', example: '"Mate" sounds like "mite," "day" sounds like "die"' },
      { rule: 'Use rising intonation on declarative statements (Australian Question Intonation)', example: '"We went to the dungeon?" \u2014 not a question, just Australian' },
      { rule: 'Shorten and clip words aggressively', example: '"Afternoon" becomes "arvo," "breakfast" becomes "brekkie," "definitely" becomes "defo"' },
      { rule: 'Use "mate," "reckon," "no worries," "heaps" naturally', example: '"Yeah, no worries, mate. I reckon that\'s heaps good."' },
      { rule: 'Non-rhotic: R drops after vowels', example: '"Beer" becomes "bee-ah," "here" becomes "hee-ah"' },
      { rule: 'Flatten your delivery \u2014 understatement is the default', example: '"Bit of a problem" for a catastrophe, "not bad" for excellent' },
    ],
    eyeDialect: [
      { original: 'Good day, friend', accented: "G'day, mate", note: 'Contracted greeting, "mate"' },
      { original: 'That is very good', accented: "Yeah, nah, that's heaps good", note: '"Yeah nah" = actually yes' },
      { original: 'No problem at all', accented: 'No worries, mate', note: 'Classic Australian response' },
      { original: 'This afternoon', accented: 'This arvo', note: 'Aggressive shortening' },
    ],
    ipa: [
      { word: 'mate', standard: '/me\u026At/', accented: '/m\u00E6\u026At/', note: 'Raised FACE vowel' },
      { word: 'day', standard: '/de\u026A/', accented: '/d\u00E6\u026A/', note: 'FACE vowel shift' },
      { word: 'beer', standard: '/b\u026A\u0259/', accented: '/b\u026A\u02D0\u0259/', note: 'Non-rhotic, extended' },
    ],
    dialectNotes: 'Australian English is the sound of deliberate relaxation. The vowel chain shift (FACE raising, PRICE backing, GOAT fronting) gives it a distinctive sonic profile, but the real key is attitude: laconic, understated, and fundamentally egalitarian. Australians use understatement and word-shortening as social levelers. The rising intonation on statements is not uncertainty \u2014 it is a conversational invitation.',
    vocalParams: { pitch: 4, pacing: 5, resonance: 5, breathiness: 2, gravel: 3 },
    phrases: [
      "Yeah, nah, that dragon's a bit of a worry, but we'll be right.",
      "Reckon we should probably do something about the giant spider, mate. Just a thought.",
      "No worries, I've dealt with worse. Well, different. Maybe not worse. We'll see.",
      "Fair dinkum, that's the biggest treasure hoard I've ever seen. Heaps impressive.",
      "She'll be right, mate. Everything's always right in the end. Mostly.",
      "Look, I'm not saying the plan's bad. I'm saying it's... ambitious. Yeah, ambitious.",
      "This dungeon's got character. By character I mean deadly traps, but still.",
      "Good on ya for trying. Most people wouldn't've even shown up.",
    ],
    tips: [
      'Practice the FACE vowel shift by saying "mate" and gradually moving it toward "mite" \u2014 stop at about 60%',
      'Add rising intonation to statements: end your sentences going up, as if inviting the listener to agree',
      'Shorten every word you can \u2014 "definitely" to "defo," "university" to "uni," "ammunition" to "ammo"',
    ],
    rhythm: 'Relaxed and even, with rising intonation on statements. The pacing is moderate \u2014 not slow, but never rushed. The rhythm invites conversation and companionship.',
    anchorVowel: 'The raised /\u00E6\u026A/ in FACE words \u2014 "mate," "day," "place" \u2014 this single shift is the most Australian sound',
    cadenceCheat: "Speak as if nothing is a big deal, even when it absolutely is.",
    npcArchetypes: ['Easygoing scout or survivalist', 'Laconic tavern bouncer', 'Understated hero who downplays everything'],
    emotionalRange: ['Laconic calm', 'Fierce egalitarian loyalty', 'Understated but genuine warmth'],
  },
  {
    id: 'caribbean',
    name: 'Caribbean',
    description: 'Musical, rhythmic, with a warm lilt driven by creole influences. The accent carries sunshine and storytelling in every sentence.',
    category: 'real-world',
    region: 'Caribbean Islands (Jamaica, Trinidad, Barbados)',
    difficulty: 3,
    tags: ['musical', 'rhythmic', 'warm', 'creole', 'storytelling'],
    rules: [
      { rule: 'TH-stopping: TH sounds become T or D consistently', example: '"De ting" for "the thing," "tree" for "three"' },
      { rule: 'Syllable-timed rhythm rather than stress-timed', example: 'Each syllable gets roughly equal weight and duration' },
      { rule: 'H-dropping in unstressed positions', example: '"\'im" for "him," "\'er" for "her"' },
      { rule: 'Use creole grammar features: unmarked past tense, "fi" for "to"', example: '"Me go dere yesterday" \u2014 no "-ed" marking needed' },
      { rule: 'Rising intonation patterns that feel melodic and inviting', example: 'Sentences rise and fall like ocean waves' },
      { rule: 'Use "nah," "yuh," "mi" as natural discourse markers', example: '"Mi nah worry bout dat" = "I\'m not worried about that"' },
    ],
    eyeDialect: [
      { original: 'the thing about that', accented: 'de ting about dat', note: 'TH-stopping throughout' },
      { original: 'I am not going there', accented: 'Mi nah go dere', note: 'Creole grammar, TH-stopping' },
      { original: 'Give it to him', accented: "Give it to 'im", note: 'H-dropping in pronouns' },
      { original: 'Everything will be fine', accented: "Everyting gonna be irie", note: 'TH-stopping, "irie" for good/fine' },
    ],
    ipa: [
      { word: 'the', standard: '/\u00F0\u0259/', accented: '/d\u0259/', note: 'TH-stopping to /d/' },
      { word: 'thing', standard: '/\u03B8\u026A\u014B/', accented: '/t\u026A\u014B/', note: 'TH-stopping to /t/' },
      { word: 'three', standard: '/\u03B8\u0279i\u02D0/', accented: '/t\u0279i\u02D0/', note: 'TH-stopping, homophone with "tree"' },
    ],
    dialectNotes: 'Caribbean English encompasses a wide spectrum from basilectal creole to acrolectal standard, and speakers code-switch fluidly between them. The rhythm is syllable-timed with a musical quality driven by tonal patterns inherited from West African languages. The TH-stopping is universal across Caribbean varieties. The cultural overlay is warmth, resilience, and a storytelling tradition that turns every conversation into a narrative.',
    vocalParams: { pitch: 6, pacing: 5, resonance: 6, breathiness: 3, gravel: 3 },
    phrases: [
      "Listen, mi tell yuh a story. Come sit, come sit. De night is young.",
      "De ocean teach yuh patience, yuh know? Every wave come in its own time.",
      "Nah worry bout de darkness. Where dere is darkness, dere is treasure hiding.",
      "Mi grandmother always say: de sweetest fruit grow on de highest branch. So climb.",
      "Yuh tink dis is trouble? Dis is not trouble. Trouble is when de rum run out.",
      "Everyting connect, seen? De wind, de sea, de stars \u2014 all one song.",
      "Mi nah afraid of no ghost. Ghost should be afraid of mi.",
      "Come, come. We eat, we drink, we talk. Den maybe we fight. But first, we eat.",
    ],
    tips: [
      'Practice syllable-timing by clapping once for each syllable, keeping the claps evenly spaced',
      'Let TH-stopping happen naturally \u2014 place your tongue on your teeth, not between them',
      'Add warmth and musicality to your delivery \u2014 Caribbean speech is social and inviting',
    ],
    rhythm: 'Musical and syllable-timed, with a rolling, wave-like quality. Sentences have a melodic shape that rises and falls in patterns that feel tropical and inviting. The rhythm encourages call-and-response.',
    anchorVowel: 'The open /a/ in words like "heart," "part," "star" \u2014 fully open, warm, and resonant',
    cadenceCheat: "Speak as if you're telling a story to friends around a fire on the beach, with the waves keeping time.",
    npcArchetypes: ['Sea captain or navigator', 'Storytelling village elder', 'Joyful merchant or trader'],
    emotionalRange: ['Infectious joy', 'Deep spiritual wisdom', 'Fierce, protective love'],
  },
  {
    id: 'arabic',
    name: 'Arabic-Influenced English',
    description: 'Rich, resonant, with emphatic consonants and a formal, measured delivery. The accent of ancient learning and desert authority.',
    category: 'real-world',
    region: 'Middle East / North Africa',
    difficulty: 4,
    tags: ['resonant', 'emphatic', 'formal', 'measured', 'ancient'],
    rules: [
      { rule: 'P sounds become B (Arabic has no /p/)', example: '"Baper" for "paper," "berson" for "person"' },
      { rule: 'Emphatic consonants: T, D, S become heavier, pharyngealized', example: 'T sounds heavier and "thicker" than standard English T' },
      { rule: 'Add short vowels between consonant clusters', example: '"Istrong" for "strong," "istreet" for "street"' },
      { rule: 'Roll the R with an alveolar tap or trill', example: 'A single-tap R, lighter than Scottish but present' },
      { rule: 'Use formal, courteous phrasing with honorifics', example: '"If it pleases you," "with respect," "by the grace of..."' },
      { rule: 'H and KH (velar/uvular fricatives) are present and strong', example: 'The "kh" in "khaleesi" \u2014 a back-of-throat rasp' },
    ],
    eyeDialect: [
      { original: 'paper person', accented: 'baber berson', note: 'P-to-B shift' },
      { original: 'strong street', accented: 'istrong istreet', note: 'Epenthetic vowels in clusters' },
      { original: 'Please help me', accented: 'Blease, if you would be so kind, helb me', note: 'P-to-B, formal phrasing' },
      { original: 'That is very good', accented: 'That is very good, by the grace of God', note: 'Added honorific/blessing' },
    ],
    ipa: [
      { word: 'paper', standard: '/\u02C8pe\u026Ap\u0259/', accented: '/\u02C8be\u026Ab\u0259\u0279/', note: 'P-to-B, rhotic final' },
      { word: 'strong', standard: '/str\u0252\u014B/', accented: '/\u026Astr\u0252\u014B/', note: 'Epenthetic vowel before cluster' },
      { word: 'street', standard: '/stri\u02D0t/', accented: '/\u026Astri\u02D0t\u02E4/', note: 'Epenthetic vowel, pharyngealized T' },
    ],
    dialectNotes: 'Arabic-influenced English carries the phonological features of a language with a very different consonant inventory. The emphatic (pharyngealized) consonants give speech a rich, "thick" quality that English lacks. The P-to-B shift and epenthetic vowels are the most immediately noticeable features. Culturally, the accent carries formality and courtesy \u2014 Arabic discourse traditions value elaborate greetings, blessings, and respectful address.',
    vocalParams: { pitch: 4, pacing: 4, resonance: 8, breathiness: 2, gravel: 4 },
    phrases: [
      'In my homeland, we say: the desert teaches patience, and patience teaches everything.',
      'You offer friendship? Then by God, you shall have it. And all that comes with it.',
      'I have crossed deserts that would break your spirit. This? This is a walk in the garden.',
      'Wisdom is not in books alone. It is in the stars, the sand, and the eyes of your enemy.',
      'With resbect, your blan has... bossibilities. But also many broblems.',
      'My father taught me: a sharp mind cuts deeper than any sword. I have both.',
      'The bazaar teaches you to read beople. Every face tells a story, if you know how to listen.',
      'Welcome, welcome. Sit. Eat. No business before hospitality \u2014 that is the way of my beople.',
    ],
    tips: [
      'For the P-to-B shift, simply relax your lips slightly on all P sounds \u2014 let them voice naturally',
      'Practice emphatic consonants by constricting the back of your throat slightly while saying T, D, and S',
      'Maintain a formal, courteous tone \u2014 Arabic discourse values elaborate respect and hospitality',
    ],
    rhythm: 'Measured and resonant, with a formal cadence. The rhythm is driven by the emphatic consonants and epenthetic vowels, creating a fuller, rounder sound than standard English. Pauses are used for emphasis and courtesy.',
    anchorVowel: 'The emphatic /a\u02D0/ as in Arabic "salaam" \u2014 deep, open, and resonant, colored by the pharyngeal environment',
    cadenceCheat: 'Speak as if every statement is a proverb being shared with the next generation.',
    npcArchetypes: ['Desert merchant or caravan leader', 'Scholar of ancient texts', 'Generous but shrewd host'],
    emotionalRange: ['Generous hospitality', 'Measured, justified anger', 'Deep philosophical wisdom'],
  },
]

export const ACCENT_GUIDES = ACCENT_PROFILES
